// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB792Hl5jxu3pXStYIXGrYV_1KNDtrIxmY',
    appId: '1:400120872345:web:a12639913d068cabbde708',
    messagingSenderId: '400120872345',
    projectId: 'animena-501bf',
    authDomain: 'animena-501bf.firebaseapp.com',
    storageBucket: 'animena-501bf.appspot.com',
    measurementId: 'G-MNG01YFR2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeIV_mb2s5tqeOishhZLA_Biz-TgmUAO8',
    appId: '1:400120872345:android:084d50e96cf13e39bde708',
    messagingSenderId: '400120872345',
    projectId: 'animena-501bf',
    storageBucket: 'animena-501bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvE8GLYhn3kFGW8Aybkc-jfdTKPESIEk8',
    appId: '1:400120872345:ios:171a9c594505b0d0bde708',
    messagingSenderId: '400120872345',
    projectId: 'animena-501bf',
    storageBucket: 'animena-501bf.appspot.com',
    iosBundleId: 'com.example.animena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvE8GLYhn3kFGW8Aybkc-jfdTKPESIEk8',
    appId: '1:400120872345:ios:171a9c594505b0d0bde708',
    messagingSenderId: '400120872345',
    projectId: 'animena-501bf',
    storageBucket: 'animena-501bf.appspot.com',
    iosBundleId: 'com.example.animena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB792Hl5jxu3pXStYIXGrYV_1KNDtrIxmY',
    appId: '1:400120872345:web:4c2b2e403295815ebde708',
    messagingSenderId: '400120872345',
    projectId: 'animena-501bf',
    authDomain: 'animena-501bf.firebaseapp.com',
    storageBucket: 'animena-501bf.appspot.com',
    measurementId: 'G-D2PX70XM76',
  );
}
