// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjwGE0n7t02PXJ7WGaK8GEfT5o4HJOi6Y',
    appId: '1:90113081358:web:4cea774f795ea42179fc5f',
    messagingSenderId: '90113081358',
    projectId: 'robust-root-441008-k6',
    authDomain: 'robust-root-441008-k6.firebaseapp.com',
    storageBucket: 'robust-root-441008-k6.firebasestorage.app',
    measurementId: 'G-9060WSC17B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7M7G-Yi2G6PoZo8zSkPGmIFDn6nwWp4g',
    appId: '1:90113081358:android:b7e4971f216a9f6379fc5f',
    messagingSenderId: '90113081358',
    projectId: 'robust-root-441008-k6',
    storageBucket: 'robust-root-441008-k6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhMjihci7pbxAIdaPIW6Sp-1-coQP9-SE',
    appId: '1:90113081358:ios:320319769701bd0579fc5f',
    messagingSenderId: '90113081358',
    projectId: 'robust-root-441008-k6',
    storageBucket: 'robust-root-441008-k6.firebasestorage.app',
    iosBundleId: 'com.example.animena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhMjihci7pbxAIdaPIW6Sp-1-coQP9-SE',
    appId: '1:90113081358:ios:320319769701bd0579fc5f',
    messagingSenderId: '90113081358',
    projectId: 'robust-root-441008-k6',
    storageBucket: 'robust-root-441008-k6.firebasestorage.app',
    iosBundleId: 'com.example.animena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjwGE0n7t02PXJ7WGaK8GEfT5o4HJOi6Y',
    appId: '1:90113081358:web:de00390193a16a4879fc5f',
    messagingSenderId: '90113081358',
    projectId: 'robust-root-441008-k6',
    authDomain: 'robust-root-441008-k6.firebaseapp.com',
    storageBucket: 'robust-root-441008-k6.firebasestorage.app',
    measurementId: 'G-WNY44L2JZ0',
  );
}
